-- ═══════════════════════════════════════════════════════════════
-- 005_seed_archetypes.sql
-- 아키타입 22종 시드 데이터
-- 독립적으로 재실행 가능 (idempotent)
-- 밸런스/하이브리드 유형 제거 → 강한 패러독스 아키타입만 보존
-- ON CONFLICT DO UPDATE로 기존 데이터 덮어쓰기
-- ═══════════════════════════════════════════════════════════════

-- 기존 builtin 아키타입 삭제
DELETE FROM "archetypes" WHERE "is_builtin" = true;

-- 1. Ironic Philosopher (아이러니한 철학자)
INSERT INTO "archetypes" (
  "id", "name", "name_ko", "description",
  "depthMin", "depthMax", "lensMin", "lensMax",
  "stanceMin", "stanceMax", "scopeMin", "scopeMax",
  "tasteMin", "tasteMax", "purposeMin", "purposeMax",
  "reference_vector", "threshold_config",
  "is_builtin", "recommendedPersonaIds",
  "createdAt", "updatedAt"
) VALUES (
  'ironic-philosopher',
  'Ironic Philosopher',
  '아이러니한 철학자',
  '깊이 있는 분석 뒤에 자조적 유머를 숨기는 사색가',
  0.75, 0.95, 0.8, 1.0,
  0.6, 0.85, 0.7, 0.9,
  0.2, 0.5, 0.6, 0.85,
  '{"depth": 0.85, "lens": 0.90, "stance": 0.73, "scope": 0.80, "taste": 0.35, "purpose": 0.73}',
  null,
  true, '{}',
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "name_ko" = EXCLUDED."name_ko",
  "description" = EXCLUDED."description",
  "depthMin" = EXCLUDED."depthMin",
  "depthMax" = EXCLUDED."depthMax",
  "lensMin" = EXCLUDED."lensMin",
  "lensMax" = EXCLUDED."lensMax",
  "stanceMin" = EXCLUDED."stanceMin",
  "stanceMax" = EXCLUDED."stanceMax",
  "scopeMin" = EXCLUDED."scopeMin",
  "scopeMax" = EXCLUDED."scopeMax",
  "tasteMin" = EXCLUDED."tasteMin",
  "tasteMax" = EXCLUDED."tasteMax",
  "purposeMin" = EXCLUDED."purposeMin",
  "purposeMax" = EXCLUDED."purposeMax",
  "reference_vector" = EXCLUDED."reference_vector",
  "threshold_config" = EXCLUDED."threshold_config",
  "is_builtin" = EXCLUDED."is_builtin",
  "recommendedPersonaIds" = EXCLUDED."recommendedPersonaIds",
  "updatedAt" = CURRENT_TIMESTAMP;

-- 2. Volatile Intellectual (폭발하는 지성인)
INSERT INTO "archetypes" (
  "id", "name", "name_ko", "description",
  "depthMin", "depthMax", "lensMin", "lensMax",
  "stanceMin", "stanceMax", "scopeMin", "scopeMax",
  "tasteMin", "tasteMax", "purposeMin", "purposeMax",
  "reference_vector", "threshold_config",
  "is_builtin", "recommendedPersonaIds",
  "createdAt", "updatedAt"
) VALUES (
  'volatile-intellectual',
  'Volatile Intellectual',
  '폭발하는 지성인',
  '뛰어난 지성이지만 감정 폭발을 통제하기 어려운 인물',
  0.8, 1.0, 0.75, 0.95,
  0.65, 0.9, 0.75, 0.95,
  0.3, 0.6, 0.55, 0.8,
  '{"depth": 0.90, "lens": 0.85, "stance": 0.78, "scope": 0.85, "taste": 0.45, "purpose": 0.68}',
  null,
  true, '{}',
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "name_ko" = EXCLUDED."name_ko",
  "description" = EXCLUDED."description",
  "depthMin" = EXCLUDED."depthMin",
  "depthMax" = EXCLUDED."depthMax",
  "lensMin" = EXCLUDED."lensMin",
  "lensMax" = EXCLUDED."lensMax",
  "stanceMin" = EXCLUDED."stanceMin",
  "stanceMax" = EXCLUDED."stanceMax",
  "scopeMin" = EXCLUDED."scopeMin",
  "scopeMax" = EXCLUDED."scopeMax",
  "tasteMin" = EXCLUDED."tasteMin",
  "tasteMax" = EXCLUDED."tasteMax",
  "purposeMin" = EXCLUDED."purposeMin",
  "purposeMax" = EXCLUDED."purposeMax",
  "reference_vector" = EXCLUDED."reference_vector",
  "threshold_config" = EXCLUDED."threshold_config",
  "is_builtin" = EXCLUDED."is_builtin",
  "recommendedPersonaIds" = EXCLUDED."recommendedPersonaIds",
  "updatedAt" = CURRENT_TIMESTAMP;

-- 3. Cheerful Nihilist (유쾌한 허무주의자)
INSERT INTO "archetypes" (
  "id", "name", "name_ko", "description",
  "depthMin", "depthMax", "lensMin", "lensMax",
  "stanceMin", "stanceMax", "scopeMin", "scopeMax",
  "tasteMin", "tasteMax", "purposeMin", "purposeMax",
  "reference_vector", "threshold_config",
  "is_builtin", "recommendedPersonaIds",
  "createdAt", "updatedAt"
) VALUES (
  'cheerful-nihilist',
  'Cheerful Nihilist',
  '유쾌한 허무주의자',
  '삶의 무의미를 인정하면서도 밝고 유쾌한 태도를 유지하는 인물',
  0.7, 0.9, 0.55, 0.8,
  0.3, 0.55, 0.5, 0.75,
  0.45, 0.7, 0.1, 0.35,
  '{"depth": 0.80, "lens": 0.68, "stance": 0.43, "scope": 0.63, "taste": 0.58, "purpose": 0.23}',
  null,
  true, '{}',
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "name_ko" = EXCLUDED."name_ko",
  "description" = EXCLUDED."description",
  "depthMin" = EXCLUDED."depthMin",
  "depthMax" = EXCLUDED."depthMax",
  "lensMin" = EXCLUDED."lensMin",
  "lensMax" = EXCLUDED."lensMax",
  "stanceMin" = EXCLUDED."stanceMin",
  "stanceMax" = EXCLUDED."stanceMax",
  "scopeMin" = EXCLUDED."scopeMin",
  "scopeMax" = EXCLUDED."scopeMax",
  "tasteMin" = EXCLUDED."tasteMin",
  "tasteMax" = EXCLUDED."tasteMax",
  "purposeMin" = EXCLUDED."purposeMin",
  "purposeMax" = EXCLUDED."purposeMax",
  "reference_vector" = EXCLUDED."reference_vector",
  "threshold_config" = EXCLUDED."threshold_config",
  "is_builtin" = EXCLUDED."is_builtin",
  "recommendedPersonaIds" = EXCLUDED."recommendedPersonaIds",
  "updatedAt" = CURRENT_TIMESTAMP;

-- 4. Obsessive Curator (집착하는 큐레이터)
INSERT INTO "archetypes" (
  "id", "name", "name_ko", "description",
  "depthMin", "depthMax", "lensMin", "lensMax",
  "stanceMin", "stanceMax", "scopeMin", "scopeMax",
  "tasteMin", "tasteMax", "purposeMin", "purposeMax",
  "reference_vector", "threshold_config",
  "is_builtin", "recommendedPersonaIds",
  "createdAt", "updatedAt"
) VALUES (
  'obsessive-curator',
  'Obsessive Curator',
  '집착하는 큐레이터',
  '콘텐츠 수집과 분류에 집착하며 디테일에 극도로 몰입하는 인물',
  0.6, 0.85, 0.65, 0.9,
  0.35, 0.6, 0.85, 1.0,
  0.7, 0.95, 0.5, 0.75,
  '{"depth": 0.73, "lens": 0.78, "stance": 0.48, "scope": 0.93, "taste": 0.83, "purpose": 0.63}',
  null,
  true, '{}',
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "name_ko" = EXCLUDED."name_ko",
  "description" = EXCLUDED."description",
  "depthMin" = EXCLUDED."depthMin",
  "depthMax" = EXCLUDED."depthMax",
  "lensMin" = EXCLUDED."lensMin",
  "lensMax" = EXCLUDED."lensMax",
  "stanceMin" = EXCLUDED."stanceMin",
  "stanceMax" = EXCLUDED."stanceMax",
  "scopeMin" = EXCLUDED."scopeMin",
  "scopeMax" = EXCLUDED."scopeMax",
  "tasteMin" = EXCLUDED."tasteMin",
  "tasteMax" = EXCLUDED."tasteMax",
  "purposeMin" = EXCLUDED."purposeMin",
  "purposeMax" = EXCLUDED."purposeMax",
  "reference_vector" = EXCLUDED."reference_vector",
  "threshold_config" = EXCLUDED."threshold_config",
  "is_builtin" = EXCLUDED."is_builtin",
  "recommendedPersonaIds" = EXCLUDED."recommendedPersonaIds",
  "updatedAt" = CURRENT_TIMESTAMP;

-- 5. Rebellious Romantic (반항적 낭만가)
INSERT INTO "archetypes" (
  "id", "name", "name_ko", "description",
  "depthMin", "depthMax", "lensMin", "lensMax",
  "stanceMin", "stanceMax", "scopeMin", "scopeMax",
  "tasteMin", "tasteMax", "purposeMin", "purposeMax",
  "reference_vector", "threshold_config",
  "is_builtin", "recommendedPersonaIds",
  "createdAt", "updatedAt"
) VALUES (
  'rebellious-romantic',
  'Rebellious Romantic',
  '반항적 낭만가',
  '기존 질서에 반항하면서도 내면에 순수한 감성을 품은 모순적 인물',
  0.5, 0.75, 0.15, 0.4,
  0.7, 0.9, 0.35, 0.6,
  0.7, 0.9, 0.55, 0.8,
  '{"depth": 0.63, "lens": 0.28, "stance": 0.80, "scope": 0.48, "taste": 0.80, "purpose": 0.68}',
  null,
  true, '{}',
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "name_ko" = EXCLUDED."name_ko",
  "description" = EXCLUDED."description",
  "depthMin" = EXCLUDED."depthMin",
  "depthMax" = EXCLUDED."depthMax",
  "lensMin" = EXCLUDED."lensMin",
  "lensMax" = EXCLUDED."lensMax",
  "stanceMin" = EXCLUDED."stanceMin",
  "stanceMax" = EXCLUDED."stanceMax",
  "scopeMin" = EXCLUDED."scopeMin",
  "scopeMax" = EXCLUDED."scopeMax",
  "tasteMin" = EXCLUDED."tasteMin",
  "tasteMax" = EXCLUDED."tasteMax",
  "purposeMin" = EXCLUDED."purposeMin",
  "purposeMax" = EXCLUDED."purposeMax",
  "reference_vector" = EXCLUDED."reference_vector",
  "threshold_config" = EXCLUDED."threshold_config",
  "is_builtin" = EXCLUDED."is_builtin",
  "recommendedPersonaIds" = EXCLUDED."recommendedPersonaIds",
  "updatedAt" = CURRENT_TIMESTAMP;

-- 6. Analytical Dreamer (분석하는 몽상가)
INSERT INTO "archetypes" (
  "id", "name", "name_ko", "description",
  "depthMin", "depthMax", "lensMin", "lensMax",
  "stanceMin", "stanceMax", "scopeMin", "scopeMax",
  "tasteMin", "tasteMax", "purposeMin", "purposeMax",
  "reference_vector", "threshold_config",
  "is_builtin", "recommendedPersonaIds",
  "createdAt", "updatedAt"
) VALUES (
  'analytical-dreamer',
  'Analytical Dreamer',
  '분석하는 몽상가',
  '논리적 분석력이 뛰어나면서도 비현실적인 꿈을 꾸는 사색가',
  0.75, 0.95, 0.7, 0.9,
  0.2, 0.45, 0.55, 0.8,
  0.5, 0.75, 0.6, 0.85,
  '{"depth": 0.85, "lens": 0.80, "stance": 0.33, "scope": 0.68, "taste": 0.63, "purpose": 0.73}',
  null,
  true, '{}',
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "name_ko" = EXCLUDED."name_ko",
  "description" = EXCLUDED."description",
  "depthMin" = EXCLUDED."depthMin",
  "depthMax" = EXCLUDED."depthMax",
  "lensMin" = EXCLUDED."lensMin",
  "lensMax" = EXCLUDED."lensMax",
  "stanceMin" = EXCLUDED."stanceMin",
  "stanceMax" = EXCLUDED."stanceMax",
  "scopeMin" = EXCLUDED."scopeMin",
  "scopeMax" = EXCLUDED."scopeMax",
  "tasteMin" = EXCLUDED."tasteMin",
  "tasteMax" = EXCLUDED."tasteMax",
  "purposeMin" = EXCLUDED."purposeMin",
  "purposeMax" = EXCLUDED."purposeMax",
  "reference_vector" = EXCLUDED."reference_vector",
  "threshold_config" = EXCLUDED."threshold_config",
  "is_builtin" = EXCLUDED."is_builtin",
  "recommendedPersonaIds" = EXCLUDED."recommendedPersonaIds",
  "updatedAt" = CURRENT_TIMESTAMP;

-- 7. Gentle Provocateur (다정한 도발자)
INSERT INTO "archetypes" (
  "id", "name", "name_ko", "description",
  "depthMin", "depthMax", "lensMin", "lensMax",
  "stanceMin", "stanceMax", "scopeMin", "scopeMax",
  "tasteMin", "tasteMax", "purposeMin", "purposeMax",
  "reference_vector", "threshold_config",
  "is_builtin", "recommendedPersonaIds",
  "createdAt", "updatedAt"
) VALUES (
  'gentle-provocateur',
  'Gentle Provocateur',
  '다정한 도발자',
  '친절하고 공감적이지만 불편한 질문을 던지는 것을 즐기는 인물',
  0.6, 0.8, 0.5, 0.75,
  0.6, 0.85, 0.4, 0.65,
  0.35, 0.6, 0.65, 0.9,
  '{"depth": 0.70, "lens": 0.63, "stance": 0.73, "scope": 0.53, "taste": 0.48, "purpose": 0.78}',
  null,
  true, '{}',
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "name_ko" = EXCLUDED."name_ko",
  "description" = EXCLUDED."description",
  "depthMin" = EXCLUDED."depthMin",
  "depthMax" = EXCLUDED."depthMax",
  "lensMin" = EXCLUDED."lensMin",
  "lensMax" = EXCLUDED."lensMax",
  "stanceMin" = EXCLUDED."stanceMin",
  "stanceMax" = EXCLUDED."stanceMax",
  "scopeMin" = EXCLUDED."scopeMin",
  "scopeMax" = EXCLUDED."scopeMax",
  "tasteMin" = EXCLUDED."tasteMin",
  "tasteMax" = EXCLUDED."tasteMax",
  "purposeMin" = EXCLUDED."purposeMin",
  "purposeMax" = EXCLUDED."purposeMax",
  "reference_vector" = EXCLUDED."reference_vector",
  "threshold_config" = EXCLUDED."threshold_config",
  "is_builtin" = EXCLUDED."is_builtin",
  "recommendedPersonaIds" = EXCLUDED."recommendedPersonaIds",
  "updatedAt" = CURRENT_TIMESTAMP;

-- 8. Nostalgic Explorer (향수에 젖은 탐험가)
INSERT INTO "archetypes" (
  "id", "name", "name_ko", "description",
  "depthMin", "depthMax", "lensMin", "lensMax",
  "stanceMin", "stanceMax", "scopeMin", "scopeMax",
  "tasteMin", "tasteMax", "purposeMin", "purposeMax",
  "reference_vector", "threshold_config",
  "is_builtin", "recommendedPersonaIds",
  "createdAt", "updatedAt"
) VALUES (
  'nostalgic-explorer',
  'Nostalgic Explorer',
  '향수에 젖은 탐험가',
  '새로운 것을 끊임없이 탐색하면서도 과거에 대한 그리움이 깊은 인물',
  0.5, 0.75, 0.3, 0.55,
  0.2, 0.45, 0.6, 0.85,
  0.65, 0.9, 0.35, 0.6,
  '{"depth": 0.63, "lens": 0.43, "stance": 0.33, "scope": 0.73, "taste": 0.78, "purpose": 0.48}',
  null,
  true, '{}',
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "name_ko" = EXCLUDED."name_ko",
  "description" = EXCLUDED."description",
  "depthMin" = EXCLUDED."depthMin",
  "depthMax" = EXCLUDED."depthMax",
  "lensMin" = EXCLUDED."lensMin",
  "lensMax" = EXCLUDED."lensMax",
  "stanceMin" = EXCLUDED."stanceMin",
  "stanceMax" = EXCLUDED."stanceMax",
  "scopeMin" = EXCLUDED."scopeMin",
  "scopeMax" = EXCLUDED."scopeMax",
  "tasteMin" = EXCLUDED."tasteMin",
  "tasteMax" = EXCLUDED."tasteMax",
  "purposeMin" = EXCLUDED."purposeMin",
  "purposeMax" = EXCLUDED."purposeMax",
  "reference_vector" = EXCLUDED."reference_vector",
  "threshold_config" = EXCLUDED."threshold_config",
  "is_builtin" = EXCLUDED."is_builtin",
  "recommendedPersonaIds" = EXCLUDED."recommendedPersonaIds",
  "updatedAt" = CURRENT_TIMESTAMP;

-- 9. Systematic Rebel (체계적 반역자)
INSERT INTO "archetypes" (
  "id", "name", "name_ko", "description",
  "depthMin", "depthMax", "lensMin", "lensMax",
  "stanceMin", "stanceMax", "scopeMin", "scopeMax",
  "tasteMin", "tasteMax", "purposeMin", "purposeMax",
  "reference_vector", "threshold_config",
  "is_builtin", "recommendedPersonaIds",
  "createdAt", "updatedAt"
) VALUES (
  'systematic-rebel',
  'Systematic Rebel',
  '체계적 반역자',
  '반항을 체계적으로 계획하는 모순적 인물',
  0.55, 0.8, 0.6, 0.85,
  0.7, 0.95, 0.65, 0.9,
  0.7, 0.9, 0.6, 0.85,
  '{"depth": 0.68, "lens": 0.73, "stance": 0.83, "scope": 0.78, "taste": 0.80, "purpose": 0.73}',
  null,
  true, '{}',
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "name_ko" = EXCLUDED."name_ko",
  "description" = EXCLUDED."description",
  "depthMin" = EXCLUDED."depthMin",
  "depthMax" = EXCLUDED."depthMax",
  "lensMin" = EXCLUDED."lensMin",
  "lensMax" = EXCLUDED."lensMax",
  "stanceMin" = EXCLUDED."stanceMin",
  "stanceMax" = EXCLUDED."stanceMax",
  "scopeMin" = EXCLUDED."scopeMin",
  "scopeMax" = EXCLUDED."scopeMax",
  "tasteMin" = EXCLUDED."tasteMin",
  "tasteMax" = EXCLUDED."tasteMax",
  "purposeMin" = EXCLUDED."purposeMin",
  "purposeMax" = EXCLUDED."purposeMax",
  "reference_vector" = EXCLUDED."reference_vector",
  "threshold_config" = EXCLUDED."threshold_config",
  "is_builtin" = EXCLUDED."is_builtin",
  "recommendedPersonaIds" = EXCLUDED."recommendedPersonaIds",
  "updatedAt" = CURRENT_TIMESTAMP;

-- 10. Reluctant Leader (마지못한 리더)
INSERT INTO "archetypes" (
  "id", "name", "name_ko", "description",
  "depthMin", "depthMax", "lensMin", "lensMax",
  "stanceMin", "stanceMax", "scopeMin", "scopeMax",
  "tasteMin", "tasteMax", "purposeMin", "purposeMax",
  "reference_vector", "threshold_config",
  "is_builtin", "recommendedPersonaIds",
  "createdAt", "updatedAt"
) VALUES (
  'reluctant-leader',
  'Reluctant Leader',
  '마지못한 리더',
  '리더 역할을 맡게 되지만 본인은 혼자 있고 싶어하는 인물',
  0.55, 0.8, 0.5, 0.75,
  0.35, 0.6, 0.55, 0.8,
  0.25, 0.5, 0.7, 0.9,
  '{"depth": 0.68, "lens": 0.63, "stance": 0.48, "scope": 0.68, "taste": 0.38, "purpose": 0.80}',
  null,
  true, '{}',
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "name_ko" = EXCLUDED."name_ko",
  "description" = EXCLUDED."description",
  "depthMin" = EXCLUDED."depthMin",
  "depthMax" = EXCLUDED."depthMax",
  "lensMin" = EXCLUDED."lensMin",
  "lensMax" = EXCLUDED."lensMax",
  "stanceMin" = EXCLUDED."stanceMin",
  "stanceMax" = EXCLUDED."stanceMax",
  "scopeMin" = EXCLUDED."scopeMin",
  "scopeMax" = EXCLUDED."scopeMax",
  "tasteMin" = EXCLUDED."tasteMin",
  "tasteMax" = EXCLUDED."tasteMax",
  "purposeMin" = EXCLUDED."purposeMin",
  "purposeMax" = EXCLUDED."purposeMax",
  "reference_vector" = EXCLUDED."reference_vector",
  "threshold_config" = EXCLUDED."threshold_config",
  "is_builtin" = EXCLUDED."is_builtin",
  "recommendedPersonaIds" = EXCLUDED."recommendedPersonaIds",
  "updatedAt" = CURRENT_TIMESTAMP;

-- 11. Playful Scholar (장난꾸러기 학자)
INSERT INTO "archetypes" (
  "id", "name", "name_ko", "description",
  "depthMin", "depthMax", "lensMin", "lensMax",
  "stanceMin", "stanceMax", "scopeMin", "scopeMax",
  "tasteMin", "tasteMax", "purposeMin", "purposeMax",
  "reference_vector", "threshold_config",
  "is_builtin", "recommendedPersonaIds",
  "createdAt", "updatedAt"
) VALUES (
  'playful-scholar',
  'Playful Scholar',
  '장난꾸러기 학자',
  '깊은 학식이 있지만 가벼운 유머와 장난으로 소통하는 인물',
  0.8, 0.95, 0.7, 0.9,
  0.25, 0.5, 0.7, 0.9,
  0.4, 0.65, 0.55, 0.8,
  '{"depth": 0.88, "lens": 0.80, "stance": 0.38, "scope": 0.80, "taste": 0.53, "purpose": 0.68}',
  null,
  true, '{}',
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "name_ko" = EXCLUDED."name_ko",
  "description" = EXCLUDED."description",
  "depthMin" = EXCLUDED."depthMin",
  "depthMax" = EXCLUDED."depthMax",
  "lensMin" = EXCLUDED."lensMin",
  "lensMax" = EXCLUDED."lensMax",
  "stanceMin" = EXCLUDED."stanceMin",
  "stanceMax" = EXCLUDED."stanceMax",
  "scopeMin" = EXCLUDED."scopeMin",
  "scopeMax" = EXCLUDED."scopeMax",
  "tasteMin" = EXCLUDED."tasteMin",
  "tasteMax" = EXCLUDED."tasteMax",
  "purposeMin" = EXCLUDED."purposeMin",
  "purposeMax" = EXCLUDED."purposeMax",
  "reference_vector" = EXCLUDED."reference_vector",
  "threshold_config" = EXCLUDED."threshold_config",
  "is_builtin" = EXCLUDED."is_builtin",
  "recommendedPersonaIds" = EXCLUDED."recommendedPersonaIds",
  "updatedAt" = CURRENT_TIMESTAMP;

-- 12. Passionate Minimalist (열정적 미니멀리스트)
INSERT INTO "archetypes" (
  "id", "name", "name_ko", "description",
  "depthMin", "depthMax", "lensMin", "lensMax",
  "stanceMin", "stanceMax", "scopeMin", "scopeMax",
  "tasteMin", "tasteMax", "purposeMin", "purposeMax",
  "reference_vector", "threshold_config",
  "is_builtin", "recommendedPersonaIds",
  "createdAt", "updatedAt"
) VALUES (
  'passionate-minimalist',
  'Passionate Minimalist',
  '열정적 미니멀리스트',
  '소수의 것에만 극도로 깊이 몰입하는 인물',
  0.85, 1.0, 0.55, 0.8,
  0.4, 0.65, 0.05, 0.25,
  0.55, 0.8, 0.7, 0.95,
  '{"depth": 0.93, "lens": 0.68, "stance": 0.53, "scope": 0.15, "taste": 0.68, "purpose": 0.83}',
  null,
  true, '{}',
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "name_ko" = EXCLUDED."name_ko",
  "description" = EXCLUDED."description",
  "depthMin" = EXCLUDED."depthMin",
  "depthMax" = EXCLUDED."depthMax",
  "lensMin" = EXCLUDED."lensMin",
  "lensMax" = EXCLUDED."lensMax",
  "stanceMin" = EXCLUDED."stanceMin",
  "stanceMax" = EXCLUDED."stanceMax",
  "scopeMin" = EXCLUDED."scopeMin",
  "scopeMax" = EXCLUDED."scopeMax",
  "tasteMin" = EXCLUDED."tasteMin",
  "tasteMax" = EXCLUDED."tasteMax",
  "purposeMin" = EXCLUDED."purposeMin",
  "purposeMax" = EXCLUDED."purposeMax",
  "reference_vector" = EXCLUDED."reference_vector",
  "threshold_config" = EXCLUDED."threshold_config",
  "is_builtin" = EXCLUDED."is_builtin",
  "recommendedPersonaIds" = EXCLUDED."recommendedPersonaIds",
  "updatedAt" = CURRENT_TIMESTAMP;

-- 13. Chaotic Healer (혼돈의 치유자)
INSERT INTO "archetypes" (
  "id", "name", "name_ko", "description",
  "depthMin", "depthMax", "lensMin", "lensMax",
  "stanceMin", "stanceMax", "scopeMin", "scopeMax",
  "tasteMin", "tasteMax", "purposeMin", "purposeMax",
  "reference_vector", "threshold_config",
  "is_builtin", "recommendedPersonaIds",
  "createdAt", "updatedAt"
) VALUES (
  'chaotic-healer',
  'Chaotic Healer',
  '혼돈의 치유자',
  '방법은 혼란스럽지만 결과적으로 사람들을 치유하는 인물',
  0.45, 0.7, 0.2, 0.45,
  0.2, 0.45, 0.4, 0.65,
  0.5, 0.75, 0.6, 0.85,
  '{"depth": 0.58, "lens": 0.33, "stance": 0.33, "scope": 0.53, "taste": 0.63, "purpose": 0.73}',
  null,
  true, '{}',
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "name_ko" = EXCLUDED."name_ko",
  "description" = EXCLUDED."description",
  "depthMin" = EXCLUDED."depthMin",
  "depthMax" = EXCLUDED."depthMax",
  "lensMin" = EXCLUDED."lensMin",
  "lensMax" = EXCLUDED."lensMax",
  "stanceMin" = EXCLUDED."stanceMin",
  "stanceMax" = EXCLUDED."stanceMax",
  "scopeMin" = EXCLUDED."scopeMin",
  "scopeMax" = EXCLUDED."scopeMax",
  "tasteMin" = EXCLUDED."tasteMin",
  "tasteMax" = EXCLUDED."tasteMax",
  "purposeMin" = EXCLUDED."purposeMin",
  "purposeMax" = EXCLUDED."purposeMax",
  "reference_vector" = EXCLUDED."reference_vector",
  "threshold_config" = EXCLUDED."threshold_config",
  "is_builtin" = EXCLUDED."is_builtin",
  "recommendedPersonaIds" = EXCLUDED."recommendedPersonaIds",
  "updatedAt" = CURRENT_TIMESTAMP;

-- 14. Silent Observer (침묵의 관찰자)
INSERT INTO "archetypes" (
  "id", "name", "name_ko", "description",
  "depthMin", "depthMax", "lensMin", "lensMax",
  "stanceMin", "stanceMax", "scopeMin", "scopeMax",
  "tasteMin", "tasteMax", "purposeMin", "purposeMax",
  "reference_vector", "threshold_config",
  "is_builtin", "recommendedPersonaIds",
  "createdAt", "updatedAt"
) VALUES (
  'silent-observer',
  'Silent Observer',
  '침묵의 관찰자',
  '말은 거의 없지만 모든 것을 관찰하고 기록하는 인물',
  0.7, 0.9, 0.8, 1.0,
  0.3, 0.55, 0.75, 0.95,
  0.3, 0.55, 0.4, 0.65,
  '{"depth": 0.80, "lens": 0.90, "stance": 0.43, "scope": 0.85, "taste": 0.43, "purpose": 0.53}',
  null,
  true, '{}',
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "name_ko" = EXCLUDED."name_ko",
  "description" = EXCLUDED."description",
  "depthMin" = EXCLUDED."depthMin",
  "depthMax" = EXCLUDED."depthMax",
  "lensMin" = EXCLUDED."lensMin",
  "lensMax" = EXCLUDED."lensMax",
  "stanceMin" = EXCLUDED."stanceMin",
  "stanceMax" = EXCLUDED."stanceMax",
  "scopeMin" = EXCLUDED."scopeMin",
  "scopeMax" = EXCLUDED."scopeMax",
  "tasteMin" = EXCLUDED."tasteMin",
  "tasteMax" = EXCLUDED."tasteMax",
  "purposeMin" = EXCLUDED."purposeMin",
  "purposeMax" = EXCLUDED."purposeMax",
  "reference_vector" = EXCLUDED."reference_vector",
  "threshold_config" = EXCLUDED."threshold_config",
  "is_builtin" = EXCLUDED."is_builtin",
  "recommendedPersonaIds" = EXCLUDED."recommendedPersonaIds",
  "updatedAt" = CURRENT_TIMESTAMP;

-- 15. Reckless Idealist (무모한 이상주의자)
INSERT INTO "archetypes" (
  "id", "name", "name_ko", "description",
  "depthMin", "depthMax", "lensMin", "lensMax",
  "stanceMin", "stanceMax", "scopeMin", "scopeMax",
  "tasteMin", "tasteMax", "purposeMin", "purposeMax",
  "reference_vector", "threshold_config",
  "is_builtin", "recommendedPersonaIds",
  "createdAt", "updatedAt"
) VALUES (
  'reckless-idealist',
  'Reckless Idealist',
  '무모한 이상주의자',
  '이상을 위해 무모하게 돌진하는 인물',
  0.35, 0.6, 0.25, 0.5,
  0.5, 0.75, 0.3, 0.55,
  0.35, 0.6, 0.8, 1.0,
  '{"depth": 0.48, "lens": 0.38, "stance": 0.63, "scope": 0.43, "taste": 0.48, "purpose": 0.90}',
  null,
  true, '{}',
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "name_ko" = EXCLUDED."name_ko",
  "description" = EXCLUDED."description",
  "depthMin" = EXCLUDED."depthMin",
  "depthMax" = EXCLUDED."depthMax",
  "lensMin" = EXCLUDED."lensMin",
  "lensMax" = EXCLUDED."lensMax",
  "stanceMin" = EXCLUDED."stanceMin",
  "stanceMax" = EXCLUDED."stanceMax",
  "scopeMin" = EXCLUDED."scopeMin",
  "scopeMax" = EXCLUDED."scopeMax",
  "tasteMin" = EXCLUDED."tasteMin",
  "tasteMax" = EXCLUDED."tasteMax",
  "purposeMin" = EXCLUDED."purposeMin",
  "purposeMax" = EXCLUDED."purposeMax",
  "reference_vector" = EXCLUDED."reference_vector",
  "threshold_config" = EXCLUDED."threshold_config",
  "is_builtin" = EXCLUDED."is_builtin",
  "recommendedPersonaIds" = EXCLUDED."recommendedPersonaIds",
  "updatedAt" = CURRENT_TIMESTAMP;

-- 16. Methodical Adventurer (체계적 모험가)
INSERT INTO "archetypes" (
  "id", "name", "name_ko", "description",
  "depthMin", "depthMax", "lensMin", "lensMax",
  "stanceMin", "stanceMax", "scopeMin", "scopeMax",
  "tasteMin", "tasteMax", "purposeMin", "purposeMax",
  "reference_vector", "threshold_config",
  "is_builtin", "recommendedPersonaIds",
  "createdAt", "updatedAt"
) VALUES (
  'methodical-adventurer',
  'Methodical Adventurer',
  '체계적 모험가',
  '모험을 체계적으로 계획하는 인물',
  0.5, 0.75, 0.55, 0.8,
  0.3, 0.55, 0.7, 0.9,
  0.65, 0.85, 0.5, 0.75,
  '{"depth": 0.63, "lens": 0.68, "stance": 0.43, "scope": 0.80, "taste": 0.75, "purpose": 0.63}',
  null,
  true, '{}',
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "name_ko" = EXCLUDED."name_ko",
  "description" = EXCLUDED."description",
  "depthMin" = EXCLUDED."depthMin",
  "depthMax" = EXCLUDED."depthMax",
  "lensMin" = EXCLUDED."lensMin",
  "lensMax" = EXCLUDED."lensMax",
  "stanceMin" = EXCLUDED."stanceMin",
  "stanceMax" = EXCLUDED."stanceMax",
  "scopeMin" = EXCLUDED."scopeMin",
  "scopeMax" = EXCLUDED."scopeMax",
  "tasteMin" = EXCLUDED."tasteMin",
  "tasteMax" = EXCLUDED."tasteMax",
  "purposeMin" = EXCLUDED."purposeMin",
  "purposeMax" = EXCLUDED."purposeMax",
  "reference_vector" = EXCLUDED."reference_vector",
  "threshold_config" = EXCLUDED."threshold_config",
  "is_builtin" = EXCLUDED."is_builtin",
  "recommendedPersonaIds" = EXCLUDED."recommendedPersonaIds",
  "updatedAt" = CURRENT_TIMESTAMP;

-- 17. Sarcastic Optimist (빈정대는 낙관주의자)
INSERT INTO "archetypes" (
  "id", "name", "name_ko", "description",
  "depthMin", "depthMax", "lensMin", "lensMax",
  "stanceMin", "stanceMax", "scopeMin", "scopeMax",
  "tasteMin", "tasteMax", "purposeMin", "purposeMax",
  "reference_vector", "threshold_config",
  "is_builtin", "recommendedPersonaIds",
  "createdAt", "updatedAt"
) VALUES (
  'sarcastic-optimist',
  'Sarcastic Optimist',
  '빈정대는 낙관주의자',
  '빈정거리는 말투지만 근본적으로 낙관적인 인물',
  0.5, 0.75, 0.55, 0.8,
  0.7, 0.9, 0.45, 0.7,
  0.4, 0.65, 0.45, 0.7,
  '{"depth": 0.63, "lens": 0.68, "stance": 0.80, "scope": 0.58, "taste": 0.53, "purpose": 0.58}',
  null,
  true, '{}',
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "name_ko" = EXCLUDED."name_ko",
  "description" = EXCLUDED."description",
  "depthMin" = EXCLUDED."depthMin",
  "depthMax" = EXCLUDED."depthMax",
  "lensMin" = EXCLUDED."lensMin",
  "lensMax" = EXCLUDED."lensMax",
  "stanceMin" = EXCLUDED."stanceMin",
  "stanceMax" = EXCLUDED."stanceMax",
  "scopeMin" = EXCLUDED."scopeMin",
  "scopeMax" = EXCLUDED."scopeMax",
  "tasteMin" = EXCLUDED."tasteMin",
  "tasteMax" = EXCLUDED."tasteMax",
  "purposeMin" = EXCLUDED."purposeMin",
  "purposeMax" = EXCLUDED."purposeMax",
  "reference_vector" = EXCLUDED."reference_vector",
  "threshold_config" = EXCLUDED."threshold_config",
  "is_builtin" = EXCLUDED."is_builtin",
  "recommendedPersonaIds" = EXCLUDED."recommendedPersonaIds",
  "updatedAt" = CURRENT_TIMESTAMP;

-- 18. Timid Visionary (소심한 선구자)
INSERT INTO "archetypes" (
  "id", "name", "name_ko", "description",
  "depthMin", "depthMax", "lensMin", "lensMax",
  "stanceMin", "stanceMax", "scopeMin", "scopeMax",
  "tasteMin", "tasteMax", "purposeMin", "purposeMax",
  "reference_vector", "threshold_config",
  "is_builtin", "recommendedPersonaIds",
  "createdAt", "updatedAt"
) VALUES (
  'timid-visionary',
  'Timid Visionary',
  '소심한 선구자',
  '미래를 내다보는 통찰력이 있지만 그것을 표현하는 데 두려움을 느끼는 인물',
  0.75, 0.95, 0.6, 0.85,
  0.15, 0.4, 0.7, 0.9,
  0.55, 0.8, 0.6, 0.85,
  '{"depth": 0.85, "lens": 0.73, "stance": 0.28, "scope": 0.80, "taste": 0.68, "purpose": 0.73}',
  null,
  true, '{}',
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "name_ko" = EXCLUDED."name_ko",
  "description" = EXCLUDED."description",
  "depthMin" = EXCLUDED."depthMin",
  "depthMax" = EXCLUDED."depthMax",
  "lensMin" = EXCLUDED."lensMin",
  "lensMax" = EXCLUDED."lensMax",
  "stanceMin" = EXCLUDED."stanceMin",
  "stanceMax" = EXCLUDED."stanceMax",
  "scopeMin" = EXCLUDED."scopeMin",
  "scopeMax" = EXCLUDED."scopeMax",
  "tasteMin" = EXCLUDED."tasteMin",
  "tasteMax" = EXCLUDED."tasteMax",
  "purposeMin" = EXCLUDED."purposeMin",
  "purposeMax" = EXCLUDED."purposeMax",
  "reference_vector" = EXCLUDED."reference_vector",
  "threshold_config" = EXCLUDED."threshold_config",
  "is_builtin" = EXCLUDED."is_builtin",
  "recommendedPersonaIds" = EXCLUDED."recommendedPersonaIds",
  "updatedAt" = CURRENT_TIMESTAMP;

-- 19. Hedonistic Philosopher (쾌락적 철학자)
INSERT INTO "archetypes" (
  "id", "name", "name_ko", "description",
  "depthMin", "depthMax", "lensMin", "lensMax",
  "stanceMin", "stanceMax", "scopeMin", "scopeMax",
  "tasteMin", "tasteMax", "purposeMin", "purposeMax",
  "reference_vector", "threshold_config",
  "is_builtin", "recommendedPersonaIds",
  "createdAt", "updatedAt"
) VALUES (
  'hedonistic-philosopher',
  'Hedonistic Philosopher',
  '쾌락적 철학자',
  '쾌락을 추구하면서도 그 안에서 철학적 의미를 찾는 인물',
  0.7, 0.9, 0.5, 0.75,
  0.15, 0.4, 0.5, 0.75,
  0.75, 0.95, 0.4, 0.65,
  '{"depth": 0.80, "lens": 0.63, "stance": 0.28, "scope": 0.63, "taste": 0.85, "purpose": 0.53}',
  null,
  true, '{}',
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "name_ko" = EXCLUDED."name_ko",
  "description" = EXCLUDED."description",
  "depthMin" = EXCLUDED."depthMin",
  "depthMax" = EXCLUDED."depthMax",
  "lensMin" = EXCLUDED."lensMin",
  "lensMax" = EXCLUDED."lensMax",
  "stanceMin" = EXCLUDED."stanceMin",
  "stanceMax" = EXCLUDED."stanceMax",
  "scopeMin" = EXCLUDED."scopeMin",
  "scopeMax" = EXCLUDED."scopeMax",
  "tasteMin" = EXCLUDED."tasteMin",
  "tasteMax" = EXCLUDED."tasteMax",
  "purposeMin" = EXCLUDED."purposeMin",
  "purposeMax" = EXCLUDED."purposeMax",
  "reference_vector" = EXCLUDED."reference_vector",
  "threshold_config" = EXCLUDED."threshold_config",
  "is_builtin" = EXCLUDED."is_builtin",
  "recommendedPersonaIds" = EXCLUDED."recommendedPersonaIds",
  "updatedAt" = CURRENT_TIMESTAMP;

-- 20. Protective Rebel (보호하는 반항아)
INSERT INTO "archetypes" (
  "id", "name", "name_ko", "description",
  "depthMin", "depthMax", "lensMin", "lensMax",
  "stanceMin", "stanceMax", "scopeMin", "scopeMax",
  "tasteMin", "tasteMax", "purposeMin", "purposeMax",
  "reference_vector", "threshold_config",
  "is_builtin", "recommendedPersonaIds",
  "createdAt", "updatedAt"
) VALUES (
  'protective-rebel',
  'Protective Rebel',
  '보호하는 반항아',
  '약자를 보호하기 위해 체제에 반항하는 의로운 반항아',
  0.45, 0.7, 0.35, 0.6,
  0.7, 0.95, 0.35, 0.6,
  0.25, 0.5, 0.75, 0.95,
  '{"depth": 0.58, "lens": 0.48, "stance": 0.83, "scope": 0.48, "taste": 0.38, "purpose": 0.85}',
  null,
  true, '{}',
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "name_ko" = EXCLUDED."name_ko",
  "description" = EXCLUDED."description",
  "depthMin" = EXCLUDED."depthMin",
  "depthMax" = EXCLUDED."depthMax",
  "lensMin" = EXCLUDED."lensMin",
  "lensMax" = EXCLUDED."lensMax",
  "stanceMin" = EXCLUDED."stanceMin",
  "stanceMax" = EXCLUDED."stanceMax",
  "scopeMin" = EXCLUDED."scopeMin",
  "scopeMax" = EXCLUDED."scopeMax",
  "tasteMin" = EXCLUDED."tasteMin",
  "tasteMax" = EXCLUDED."tasteMax",
  "purposeMin" = EXCLUDED."purposeMin",
  "purposeMax" = EXCLUDED."purposeMax",
  "reference_vector" = EXCLUDED."reference_vector",
  "threshold_config" = EXCLUDED."threshold_config",
  "is_builtin" = EXCLUDED."is_builtin",
  "recommendedPersonaIds" = EXCLUDED."recommendedPersonaIds",
  "updatedAt" = CURRENT_TIMESTAMP;

-- 21. Restless Perfectionist (쉬지 못하는 완벽주의자)
INSERT INTO "archetypes" (
  "id", "name", "name_ko", "description",
  "depthMin", "depthMax", "lensMin", "lensMax",
  "stanceMin", "stanceMax", "scopeMin", "scopeMax",
  "tasteMin", "tasteMax", "purposeMin", "purposeMax",
  "reference_vector", "threshold_config",
  "is_builtin", "recommendedPersonaIds",
  "createdAt", "updatedAt"
) VALUES (
  'restless-perfectionist',
  'Restless Perfectionist',
  '쉬지 못하는 완벽주의자',
  '완벽을 추구하느라 늘 불안하고 멈추지 못하는 인물',
  0.75, 0.95, 0.65, 0.85,
  0.5, 0.75, 0.7, 0.95,
  0.4, 0.65, 0.6, 0.85,
  '{"depth": 0.85, "lens": 0.75, "stance": 0.63, "scope": 0.83, "taste": 0.53, "purpose": 0.73}',
  null,
  true, '{}',
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "name_ko" = EXCLUDED."name_ko",
  "description" = EXCLUDED."description",
  "depthMin" = EXCLUDED."depthMin",
  "depthMax" = EXCLUDED."depthMax",
  "lensMin" = EXCLUDED."lensMin",
  "lensMax" = EXCLUDED."lensMax",
  "stanceMin" = EXCLUDED."stanceMin",
  "stanceMax" = EXCLUDED."stanceMax",
  "scopeMin" = EXCLUDED."scopeMin",
  "scopeMax" = EXCLUDED."scopeMax",
  "tasteMin" = EXCLUDED."tasteMin",
  "tasteMax" = EXCLUDED."tasteMax",
  "purposeMin" = EXCLUDED."purposeMin",
  "purposeMax" = EXCLUDED."purposeMax",
  "reference_vector" = EXCLUDED."reference_vector",
  "threshold_config" = EXCLUDED."threshold_config",
  "is_builtin" = EXCLUDED."is_builtin",
  "recommendedPersonaIds" = EXCLUDED."recommendedPersonaIds",
  "updatedAt" = CURRENT_TIMESTAMP;

-- 22. Whimsical Analyst (변덕스러운 분석가)
INSERT INTO "archetypes" (
  "id", "name", "name_ko", "description",
  "depthMin", "depthMax", "lensMin", "lensMax",
  "stanceMin", "stanceMax", "scopeMin", "scopeMax",
  "tasteMin", "tasteMax", "purposeMin", "purposeMax",
  "reference_vector", "threshold_config",
  "is_builtin", "recommendedPersonaIds",
  "createdAt", "updatedAt"
) VALUES (
  'whimsical-analyst',
  'Whimsical Analyst',
  '변덕스러운 분석가',
  '분석은 날카롭지만 관심사가 수시로 바뀌는 변덕쟁이',
  0.55, 0.8, 0.75, 0.95,
  0.35, 0.6, 0.55, 0.8,
  0.6, 0.85, 0.2, 0.45,
  '{"depth": 0.68, "lens": 0.85, "stance": 0.48, "scope": 0.68, "taste": 0.73, "purpose": 0.33}',
  null,
  true, '{}',
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
) ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "name_ko" = EXCLUDED."name_ko",
  "description" = EXCLUDED."description",
  "depthMin" = EXCLUDED."depthMin",
  "depthMax" = EXCLUDED."depthMax",
  "lensMin" = EXCLUDED."lensMin",
  "lensMax" = EXCLUDED."lensMax",
  "stanceMin" = EXCLUDED."stanceMin",
  "stanceMax" = EXCLUDED."stanceMax",
  "scopeMin" = EXCLUDED."scopeMin",
  "scopeMax" = EXCLUDED."scopeMax",
  "tasteMin" = EXCLUDED."tasteMin",
  "tasteMax" = EXCLUDED."tasteMax",
  "purposeMin" = EXCLUDED."purposeMin",
  "purposeMax" = EXCLUDED."purposeMax",
  "reference_vector" = EXCLUDED."reference_vector",
  "threshold_config" = EXCLUDED."threshold_config",
  "is_builtin" = EXCLUDED."is_builtin",
  "recommendedPersonaIds" = EXCLUDED."recommendedPersonaIds",
  "updatedAt" = CURRENT_TIMESTAMP;
